package com.jainbooks.web;

public class WebServiceConstants {

	  public static final String BASE_URL="http://ec2-54-191-72-198.us-west-2.compute.amazonaws.com:8080/JainBooks/rest/jainbook-service/";
	  public static final String GET_EBOOK_CATEGORIES="get-ebook-categories";
	  public static final String GET_EBOOK_FOR_CATEGORIES="get-ebook-categories-id?categoryId=";
	  public static final String REGISTRATION="registerUser";
	  public static final String AUTHENTICATE="authenticate";
	  public static final String GET_USER_LIBRARY="get-user-library?email=";
	 // public static final String sf ="{"categories":[{"category":{"name":"Aarti","id":4},"ebooks":[{"category":{"name":"Shakti","id":3},"created":null,"updated":null,"title":"The Story of India","author":"Triloki Nath","deleted":false,"rating":4,"summary":"Another Great EBook. Has wonderful content","thumbnailUrl":null,"id":9},{"category":{"name":"Shakti","id":3},"created":null,"updated":null,"title":"The Story of India Part 2","author":"Triloki Nath","deleted":false,"rating":3,"summary":"Another Great EBook. Has wonderful content","thumbnailUrl":null,"id":10}]},{"category":{"name":"Bhakti","id":2},"ebooks":[{"category":{"name":"Chalisa","id":1},"created":null,"updated":null,"title":"Kahani Google Glasses Ki","author":"Nitesh","deleted":false,"rating":5,"summary":"Great EBook by nitesh. Has great content","thumbnailUrl":null,"id":1},{"category":{"name":"Chalisa","id":1},"created":null,"updated":null,"title":"Kahani Google Glasses Ki Part 2","author":"Nitesh Garg","deleted":false,"rating":4,"summary":"Another Great EBook by nitesh. Has wonderful content","thumbnailUrl":null,"id":2},{"category":{"name":"Chalisa","id":1},"created":null,"updated":null,"title":"Kahani Google Glasses Ki Part 3","author":"Nitesh Garg","deleted":false,"rating":4,"summary":"Another Great EBook by nitesh. Has wonderful content","thumbnailUrl":null,"id":3},{"category":{"name":"Chalisa","id":1},"created":null,"updated":null,"title":"Kahani Google Glasses Ki Part 4","author":"Nitesh Garg","deleted":false,"rating":4,"summary":"Another Great EBook by nitesh. Has wonderful content","thumbnailUrl":null,"id":4},{"category":{"name":"Chalisa","id":1},"created":null,"updated":null,"title":"Kahani Google Glasses Ki Part 5","author":"Nitesh Garg","deleted":false,"rating":4,"summary":"Another Great EBook by nitesh. Has wonderful content","thumbnailUrl":null,"id":5}]}]}";
}
